#
# Copyright (c) 2019 by Delphix. All rights reserved.
#

---
- name: Converge
  hosts: all
  roles:
    - role: delphix.self-enroll
  pre_tasks:
    - name: Install vixie-cron
      yum:
        name: cronie
        state: present